# Generated by Django 6.0.2 on 2026-02-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('ruc', models.CharField(max_length=13, verbose_name='RUC')),
                ('direccion_matriz', models.TextField(verbose_name='Dirección Matriz')),
                ('direccion_sucursal', models.TextField(blank=True, verbose_name='Dirección Sucursal')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('establecimiento', models.CharField(default='001', max_length=3, verbose_name='Establecimiento')),
                ('punto_emision', models.CharField(default='001', max_length=3, verbose_name='Punto de Emisión')),
                ('secuencia_factura', models.PositiveIntegerField(default=1, verbose_name='Secuencial de Factura')),
                ('iva_tarifa', models.DecimalField(decimal_places=2, default=12.0, help_text='Porcentaje del IVA (12%, 14%, 15%, etc.)', max_digits=5, verbose_name='Tarifa IVA (%)')),
                ('ice_tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tarifa ICE (%)')),
                ('obligado_contabilidad', models.BooleanField(default=False, verbose_name='Obligado a llevar contabilidad')),
                ('tipo_contribuyente', models.CharField(choices=[('persona_natural', 'Persona Natural'), ('sociedad', 'Sociedad')], default='persona_natural', max_length=20, verbose_name='Tipo de Contribuyente')),
                ('resolucion_contribuyente', models.CharField(blank=True, max_length=50, verbose_name='Resolución del Contribuyente')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
