# Generated by Django 6.0.2 on 2026-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='ice_tarifa',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ambiente',
            field=models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='certificado_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Clave certificado'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='certificado_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ruta certificado (.p12)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='contribuyente_especial',
            field=models.BooleanField(default=False, verbose_name='Contribuyente Especial'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='enviar_email_auto',
            field=models.BooleanField(default=True, verbose_name='Enviar email automáticamente al cliente'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='plantilla_email',
            field=models.TextField(blank=True, help_text='Use {{cliente}}, {{numero_factura}}, {{total}} para variables', verbose_name='Plantilla email'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='regimen_tributario',
            field=models.CharField(choices=[('general', 'Régimen General'), ('rimpe', 'RIMPE'), ('rural', 'Rural')], default='general', max_length=20, verbose_name='Régimen Tributario'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='tipo_emision',
            field=models.CharField(choices=[('1', 'Normal'), ('2', 'Indisponible')], default='1', max_length=1, verbose_name='Tipo de Emisión'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='iva_tarifa',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Porcentaje del IVA (12%, 14%, 15%)', max_digits=5, verbose_name='Tarifa IVA (%)'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='resolucion_contribuyente',
            field=models.CharField(blank=True, max_length=50, verbose_name='Resolución Contribuyente Especial'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='ruc',
            field=models.CharField(help_text='13 dígitos', max_length=13, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='tipo_contribuyente',
            field=models.CharField(choices=[('persona_natural', 'Persona Natural'), ('sociedad', 'Sociedad')], default='sociedad', max_length=20, verbose_name='Tipo de Contribuyente'),
        ),
    ]
