# Generated by Django 6.0.2 on 2026-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_configuracion_ice_tarifa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='certificado_path',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='iva_tarifa',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='certificado_archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Archivo certificado (.p12)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ice_tarifa',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje Impuesto Consumos Especiales', max_digits=5, verbose_name='Tarifa ICE (%)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='irbp_tarifa',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje IRBP (solo aplicable en ciertos productos)', max_digits=5, verbose_name='Tarifa IRBP (%)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='iva_tarifa_12',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Porcentaje IVA categoría gravada', max_digits=5, verbose_name='Tarifa IVA 12%'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='iva_tarifa_14',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje IVA categoría gravada (si aplica)', max_digits=5, verbose_name='Tarifa IVA 14%'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='secuencia_guia_remision',
            field=models.PositiveIntegerField(default=1, verbose_name='Secuencial Guía Remisión'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='secuencia_nota_credito',
            field=models.PositiveIntegerField(default=1, verbose_name='Secuencial Nota Crédito'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='secuencia_nota_debito',
            field=models.PositiveIntegerField(default=1, verbose_name='Secuencial Nota Débito'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='secuencia_retencion',
            field=models.PositiveIntegerField(default=1, verbose_name='Secuencial Retención'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='secuencia_factura',
            field=models.PositiveIntegerField(default=1, verbose_name='Secuencial Factura'),
        ),
    ]
