# Generated by Django 6.0.2 on 2026-02-22 14:43

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(choices=[('consumidor_final', 'Consumidor Final'), ('ruc', 'RUC'), ('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], default='consumidor_final', max_length=20, verbose_name='Tipo de Identificación'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='codigo_auxiliar',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Auxiliar'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento (%)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='autorizacion_sri',
            field=models.TextField(blank=True, verbose_name='Autorización SRI'),
        ),
        migrations.AddField(
            model_name='venta',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=49, verbose_name='Clave de Acceso SRI'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_direccion',
            field=models.TextField(blank=True, verbose_name='Dirección Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_identificacion',
            field=models.CharField(blank=True, max_length=20, verbose_name='Identificación del Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del Cliente (Factura)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_tipo_identificacion',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo Identificación'),
        ),
        migrations.AddField(
            model_name='venta',
            name='establecimiento',
            field=models.CharField(default='001', max_length=3, verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_sri',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='pendiente', max_length=20, verbose_name='Estado SRI'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización'),
        ),
        migrations.AddField(
            model_name='venta',
            name='forma_pago_sri',
            field=models.CharField(default='01', help_text='01: Efectivo, 02: Cheque, 03: Transferencia, 04: Tarjeta Crédito, etc.', max_length=2, verbose_name='Forma de Pago SRI'),
        ),
        migrations.AddField(
            model_name='venta',
            name='ice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ICE'),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IVA 12%'),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Formato: 001-001-000000001', max_length=17, verbose_name='Número de Factura (SRI)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='punto_emision',
            field=models.CharField(default='001', max_length=3, verbose_name='Punto de Emisión'),
        ),
        migrations.AddField(
            model_name='venta',
            name='secuencia_factura',
            field=models.PositiveIntegerField(default=1, verbose_name='Secuencial de Factura'),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal_0',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal 0%'),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal_12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal 12%'),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal_exento_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal Exento IVA'),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal_no_objeto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal No Objeto IVA'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_emision',
            field=models.CharField(choices=[('normal', 'Normal'), ('indisponible', 'Indisponible')], default='normal', max_length=20, verbose_name='Tipo de Emisión'),
        ),
        migrations.AddField(
            model_name='venta',
            name='xml_factura',
            field=models.TextField(blank=True, verbose_name='XML Factura'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula/RUC/Pasaporte'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre/Razón Social'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_debito', 'Tarjeta Débito'), ('tarjeta_credito', 'Tarjeta Crédito'), ('cheque', 'Cheque'), ('diplomatico', 'Diplomático'), ('compensacion', 'Compensación'), ('otros', 'Otros')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['numero_factura'], name='ventas_vent_numero__cd1ed4_idx'),
        ),
    ]
