# Generated by Django 6.0.2 on 2026-02-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_venta_subtotal_cliente_tipo_identificacion_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_numero_575d97_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_created_73e5a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_cliente_1869ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_numero__cd1ed4_idx',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='codigo_auxiliar',
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_sri',
            field=models.CharField(default='pendiente', max_length=20, verbose_name='Estado SRI'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago_sri',
            field=models.CharField(default='01', max_length=2, verbose_name='Forma de Pago SRI'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=17, verbose_name='Número de Factura (SRI)'),
        ),
        migrations.RemoveField(
            model_name='venta',
            name='autorizacion_sri',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha_autorizacion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ice',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='subtotal_exento_iva',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='subtotal_no_objeto_iva',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tipo_emision',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='xml_factura',
        ),
    ]
