# Generated by Django 6.0.2 on 2026-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_venta_ventas_vent_numero_575d97_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_autorizacion',
            field=models.CharField(blank=True, max_length=30, verbose_name='Fecha de Autorización'),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_autorizacion',
            field=models.CharField(blank=True, max_length=49, verbose_name='Número de Autorización'),
        ),
        migrations.AddField(
            model_name='venta',
            name='xml_content',
            field=models.TextField(blank=True, verbose_name='XML del comprobante'),
        ),
        migrations.AddField(
            model_name='venta',
            name='xml_firmado',
            field=models.TextField(blank=True, verbose_name='XML firmado'),
        ),
    ]
